# Generated by Django 6.0.1 on 2026-02-06 00:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('primary_name', models.CharField(max_length=50)),
                ('secondary_name', models.CharField(blank=True, max_length=50, null=True)),
                ('first_last_name', models.CharField(max_length=50)),
                ('second_last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(max_length=10)),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('primary_name', models.CharField(max_length=50)),
                ('secondary_name', models.CharField(blank=True, max_length=50, null=True)),
                ('first_last_name', models.CharField(max_length=50)),
                ('second_last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(max_length=10)),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.player')),
            ],
        ),
    ]
