# Generated by Django 6.0.1 on 2026-02-06 02:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Outcoming',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('description', models.TextField(max_length=260)),
                ('amount', models.CharField(max_length=10)),
                ('date', models.DateField()),
            ],
        ),
    ]
