# Generated by Django 6.0.1 on 2026-02-06 00:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('physical_condition', models.CharField(choices=[('GOOD', 'Good'), ('OTHER', 'Other')], max_length=6)),
                ('condition', models.CharField(blank=True, max_length=50, null=True)),
                ('initial_date', models.DateField()),
                ('expiration_date', models.DateField()),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.player')),
            ],
        ),
    ]
