# Generated by Django 6.0.1 on 2026-02-10 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='initial_date',
            new_name='pay_date',
        ),
        migrations.AddField(
            model_name='subscription',
            name='ammount',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='subscription',
            name='single_class',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
