# Generated by Django 6.0.1 on 2026-02-17 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_rename_initial_date_subscription_pay_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='ammount',
            field=models.CharField(max_length=10),
        ),
    ]
