# Generated by Django 6.0.1 on 2026-02-18 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_alter_subscription_ammount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='single_class',
            field=models.BooleanField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], null=True),
        ),
    ]
