# Generated by Django 6.0.1 on 2026-02-18 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_alter_subscription_single_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='single_class',
            field=models.BooleanField(default=False),
        ),
    ]
