# Generated by Django 6.0.1 on 2026-04-23 00:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Uniform',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('number', models.CharField(max_length=2)),
                ('size', models.CharField(max_length=10)),
            ],
        ),
    ]
