# Generated by Django 6.0.1 on 2026-02-06 02:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniforms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('amount', models.CharField(max_length=7)),
                ('pay_date', models.DateField()),
                ('uniform_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uniforms.uniform')),
            ],
        ),
    ]
