# Generated by Django 6.0.1 on 2026-02-10 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uniforms', '0002_payment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payment',
            new_name='UniformPayment',
        ),
    ]
