# Generated by Django 6.0.1 on 2026-03-11 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniforms', '0003_rename_payment_uniformpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='uniform',
            name='production_status',
            field=models.CharField(blank=True, choices=[('Pending', 'P'), ('In Progress', 'IP'), ('Ready', 'R')], max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='uniformpayment',
            name='pay_status',
            field=models.CharField(blank=True, choices=[('Complete', 'c'), ('Payment', 'p')], max_length=10, null=True, verbose_name='Payment Status'),
        ),
    ]
