# Generated by Django 6.0.1 on 2026-03-24 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uniforms', '0004_uniform_production_status_uniformpayment_pay_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uniform',
            name='production_status',
        ),
        migrations.RemoveField(
            model_name='uniformpayment',
            name='pay_status',
        ),
    ]
