# Generated by Django 6.0.1 on 2026-04-23 00:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Outcoming',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('description', models.TextField(max_length=260)),
                ('amount', models.CharField(max_length=10)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('physical_condition', models.CharField(choices=[('GOOD', 'Good'), ('OTHER', 'Other')], max_length=6)),
                ('condition', models.CharField(blank=True, max_length=50, null=True)),
                ('single_class', models.BooleanField(default=False)),
                ('ammount', models.CharField(max_length=10)),
                ('pay_date', models.DateField()),
                ('expiration_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UniformPayment',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('amount', models.CharField(max_length=7)),
                ('pay_date', models.DateField()),
            ],
        ),
    ]
