# Generated by Django 6.0.1 on 2026-07-31 20:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Outcoming',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, max_length=260, null=True)),
                ('amount', models.CharField(blank=True, max_length=10, null=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Savings',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('ammount', models.CharField(blank=True, max_length=7, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('physical_condition', models.IntegerField(blank=True, choices=[(0, 'Good'), (1, 'Other')], null=True)),
                ('condition', models.CharField(blank=True, max_length=50, null=True)),
                ('single_class', models.BooleanField(default=False)),
                ('ammount', models.CharField(blank=True, max_length=10, null=True)),
                ('pay_date', models.DateField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UniformPayment',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('amount', models.CharField(blank=True, max_length=7, null=True)),
                ('payment_method', models.IntegerField(blank=True, choices=[(0, 'Digital'), (1, 'Cash')], null=True)),
                ('pay_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
