# Generated by Django 6.0.1 on 2026-04-15 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
        ('uniforms', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='player_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.player'),
        ),
        migrations.AddField(
            model_name='uniformpayment',
            name='uniform_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uniforms.uniform'),
        ),
    ]
