# Generated by Django 6.0.1 on 2026-05-19 00:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Savings',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('ammount', models.CharField(blank=True, max_length=7, null=True)),
            ],
        ),
    ]
